INSERT_MODE_NONE    = 0
INSERT_MODE_RECT    = 1
INSERT_MODE_POLYGON = 2
INSERT_MODE_ANY     = INSERT_MODE_RECT or INSERT_MODE_POLYGON

EDIT_MODE_NONE   = 0
EDIT_MODE_OBJECT = 1
EDIT_MODE_POINT  = 2
EDIT_MODE_TEXT   = 3
EDIT_MODE_ANY    = EDIT_MODE_OBJECT or EDIT_MODE_POINT or EDIT_MODE_TEXT